alias ctop='docker run --rm -ti --name=ctop -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
alias ddc='cd ~/plexflix && docker-compose'
alias borgmatic='ddc run --rm  borgmatic borgmatic'
alias borg='ddc run --rm borgmatic borg'
alias logerr='ddc logs -f -t --tail=1 | egrep -i "(warn|error|fail)"'
alias rclone='ddc exec rclone rclone'
alias up='ddc up -d --build'
alias wls='f() { watch -d -c ls -l --color \"$@\"; }; f'
alias upload_queue='watch -t -n 10 -d -- echo "Upload Queue: \`find ~/plexflix/data/upload -type f  | wc -l\` files, \`du -sh ~/plexflix/data/upload | cut -f1 \`"'
