#!/usr/bin/with-contenv sh

if pidof -o %PPID "upload_cloud"; then
  echo "Already running." | tee -a $LOGFILE
  exit 1
fi

LOGFILE="/logs/upload_cloud.log"
FROM=${UPLOAD_PATH}
TO=${REMOTE_PATH}

if find $FROM/* -type f -mmin +${UPLOAD_DELAY} | read; then
  echo "$(date "+%d.%m.%Y %T") RCLONE UPLOAD STARTED" | tee -a $LOGFILE
  # MOVE FILES OLDER THEN UPLOAD_DELAY MINUTES
  /usr/bin/rclone move $FROM $TO --min-age ${UPLOAD_DELAY}m  \
  --log-level=INFO ${RCLONE_UPLOAD_OPTIONS} | tee -a $LOGFILE

  echo "$(date "+%d.%m.%Y %T") RCLONE UPLOAD ENDED" | tee -a $LOGFILE
fi