#!/usr/bin/with-contenv sh

set -e

LOGFILE=/logs/upload_cloud.log
FROM=${UPLOAD_PATH}
TO=${REMOTE_PATH}
LOCKFILE="/var/run/`basename $0`"

log() {
  echo "$(date "+%Y/%m/%d %T") INFO  : $*" | tee -a $LOGFILE
}

# Avoid multiple runs
exec 200>$LOCKFILE
flock -n 200 || (log "RCLONE UPLOAD IN PROGRESS" && exit 1)
echo $$ 1>&200

# MOVE FILES OLDER THEN UPLOAD_DELAY MINUTES
if find $FROM -type f -mmin +${UPLOAD_DELAY} | grep -v downloads | read; then
  log "RCLONE UPLOAD STARTED"

  # Add excludes flag if excludes file is present in config
  if [ -f /config/excludes ]; then
    EXCLUDES="--exclude-from /config/excludes"
  fi

  /usr/bin/rclone move $FROM $TO --min-age ${UPLOAD_DELAY}m  \
    ${EXCLUDES} ${RCLONE_UPLOAD_OPTIONS} 2>&1 | tee -a $LOGFILE

  log "RCLONE UPLOAD ENDED"
fi