location:
    source_directories:
        - /mnt/source/.env
        - /mnt/source/docker-compose.override.yml
        - /mnt/source/config/borgmatic
        - /mnt/source/config/caddy
        - /mnt/source/config/jackett
        - /mnt/source/config/ombi
        - /mnt/source/config/portainer
        - /mnt/source/config/radarr
        - /mnt/source/config/rclone
        - /mnt/source/config/sonarr
        - /mnt/source/config/tautulli
        - /mnt/source/config/plex/Library/Application Support/Plex Media Server/Preferences.xml
        - /mnt/source/config/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases
    repositories:
        - /mnt/repository
    one_file_system: true

    exclude_patterns:
        - '/**/ombi/*.db-journal'
        - '/**/MediaCover/*'
        - '/**/Backups/*'
        - '/**/UpdateLogs/*'
        - '/**/backups/*'
        - '/**/cache/*'
        - '/**/logs/*'
        - '**/log*.txt'

storage:
    encryption_passphrase: "DonNotMissToChangeYourPassphrase"
    compression: lz4
    archive_name_format: 'backup-{now}'

retention:
    keep_hourly: 2
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 12
    keep_yearly: 10
    prefix: 'backup-'

consistency:
    checks:
        - repository
        - archives
    check_last: 3
    prefix: 'backup-'

hooks:
    before_backup:
        - echo "Starting a backup job."
        - date "+%Y%m%d%H%M%S" > /tmp/jobname
    after_backup:
        - /etc/borgmatic.d/upload_backup.sh 2>&1 | tee $(cat /tmp/jobname)
        - /etc/borgmatic.d/slack_send.py ":information_source:" "Backup Successful" "$(cat $(cat /tmp/jobname))"
    on_error:
        - echo "Error while creating a backup."
        - /etc/borgmatic.d/slack_send.py ":bangbang:" "Error while creating a backup" "$(cat $(cat /tmp/jobname))"
