#!/usr/bin/with-contenv sh

trap "fusermount -uz ${LOCAL_MOUNT}" EXIT

fusermount -uz ${LOCAL_MOUNT} || :
mergerfs ${MERGERFS_OPTIONS} ${UPLOAD_PATH}:${REMOTE_MOUNT}  ${LOCAL_MOUNT}

exec s6-setuidgid abc /usr/bin/rclone mount ${REMOTE_PATH} ${REMOTE_MOUNT} \
    --cache-dir /data/rclone/cache ${RCLONE_MOUNT_OPTIONS}