#!/usr/bin/with-contenv sh

# Saves the configuration to the defaut location, so it is not required to pass the 
# path on every invocation
CONFIG_FOLDER=/rclone
RCLONE_CONFIG_FILE=$CONFIG_FOLDER/rclone.conf
mkdir -p $CONFIG_FOLDER

# Create rclone's union mountpoint config
cp $CONFIG_FILE $RCLONE_CONFIG_FILE
echo "[rclone-gdrive-union]" >> $RCLONE_CONFIG_FILE
echo "type = union" >> $RCLONE_CONFIG_FILE
echo "remotes = \"${REMOTE_PATH}\" \"${UPLOAD_PATH}\"" >> $RCLONE_CONFIG_FILE

# Give read/search access to all users (not secure, I know...)
chown -R abc:abc $CONFIG_FOLDER