#!/usr/bin/with-contenv sh

# Create rclone's union mountpoint config
cp $CONFIG_FILE /rclone
echo "[rclone-gdrive-union]" >> /rclone/rclone.conf
echo "type = union" >> /rclone/rclone.conf
echo "remotes = ${REMOTE_PATH} ${UPLOAD_PATH}" >> /rclone/rclone.conf

chown -R abc:abc /rclone