#!/usr/bin/with-contenv sh

# Saves the configuration to the defaut location, so it is not required to pass the 
# path on every invocation
HOME=/rclone
CONFIG_FOLDER=${HOME}/.config/rclone
RCLONE_CONFIG_FILE=$CONFIG_FOLDER/rclone.conf
mkdir -p $CONFIG_FOLDER

# Create rclone's union mountpoint config
cp $CONFIG_FILE $RCLONE_CONFIG_FILE
# echo >> $RCLONE_CONFIG_FILE
# echo >> $RCLONE_CONFIG_FILE
# echo "[rclone-gdrive-union]" >> $RCLONE_CONFIG_FILE
# echo "type = union" >> $RCLONE_CONFIG_FILE
# echo "remotes = \"${REMOTE_PATH}\" \"${UPLOAD_PATH}\"" >> $RCLONE_CONFIG_FILE

chown -R abc:abc $HOME

# Link the config to root's home, so rclone can be called as root as well 
# without specifying the config path
mkdir -p /root/.config
ln -sf $CONFIG_FOLDER /root/.config