#!/usr/bin/with-contenv sh

cd /logs
touch cron.log rclone_mount.log upload_cloud.log
chown -R abc:abc /logs

mkdir -p ${UPLOAD_PATH} ${LOCAL_MOUNT} ${REMOTE_MOUNT}
chown abc:abc ${UPLOAD_PATH} ${LOCAL_MOUNT} ${REMOTE_MOUNT}