#!/usr/bin/with-contenv sh

# Saves a copy of the configuration to the defaut location, so it is not required to pass the 
# path on every invocation
mkdir -p /root/.config/rclone
cp $CONFIG_FILE /root/.config/rclone