#!/usr/bin/with-contenv sh

# this line here is what we should have to get rid of the hard link error
# touch /etc/crontab # /etc/cron.*/*

cat /crontab.txt >> /etc/crontabs/root

exec /usr/sbin/crond -f -l 8 -L /logs/cron.log